---
- hosts: dbservers
  roles:
    - mariadb
    # Use geerlingguy's mysql for Ubuntu
    # - geerlingguy.mysql

- hosts: openstack_identity
  roles:
    - os-keystone

- hosts: ciao_controller
  roles:
    - ciao-controller

- hosts: ciao_compute
  roles:
    - ciao-compute

- hosts: ciao_network
  roles:
    - ciao-network
