---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- block:
    - name: Install ciao webui bundle
      command: "swupd bundle-add cloud-dashboard {{ swupd_args }}"
      args:
        creates: /usr/share/clear/bundles/cloud-dashboard

    - name: Verify cloud-dashboard bundle have been installed
      command: "swupd verify -f {{ swupd_args }}"
      args:
        creates: /usr/lib/ciao-webui

    - name: Install nodejs-basic bundle
      command: "swupd bundle-add nodejs-basic {{ swupd_args }}"
      args:
        creates: /usr/share/clear/bundles/nodejs-basic
      when: ciao_dev

    - name: Verify nodejs-basic bundle have been installed
      command: "swupd verify -f {{ swupd_args }}"
      args:
        creates: /usr/bin/node
      when: ciao_dev
  when: ansible_os_family == "Clear linux software for intel architecture"

# - name: Install from sources

- name: Create /etc/ciao-webui directory
  file: path=/etc/ciao-webui state=directory

- name: Configure ciao-webui
  template: src=ciao_config.json.j2 dest=/etc/ciao-webui/ciao_config.json
