---
- hosts: ciao_controller:ciao_compute:ciao_network
  tasks:

    # In ansible 2.2.0 we can drop ignore errors since it will not fail
    # when the services does not exist.
    - name: Stop services
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - ciao-network.service
        - ciao-compute.service
        - ciao-controller.service
        - ciao-scheduler.service
      ignore_errors: yes

    - name: Remove CIAO Service files
      file: name={{ item }} state=absent
      with_items:
        - /etc/systemd/system/ciao-network.service
        - /etc/systemd/system/ciao-compute.service
        - /etc/systemd/system/ciao-scheduler.service
        - /etc/systemd/system/ciao-controller.service

    - name: Remove CIAO files
      file: path={{ item }} state=absent
      with_items:
        - /etc/ciao
        - /etc/pki/ciao
        - /var/lib/ciao
        - /etc/ssl/certs/cacert.pem
        - /etc/ca-certificates/cacert.pem
        - /usr/local/share/ca-certificates/cacert.crt

    - name: Remove CIAO files from github
      file: path={{ item }} state=absent
      with_items:
        - ~/go
        - /usr/local/bin/ciao-controller
        - /usr/local/bin/ciao-scheduler
        - /usr/local/bin/ciao-launcher
        - /usr/local/bin/ciao-cli
        - /usr/local/bin/ciao-cert
        - /usr/local/bin/ciao-cnci-agent
      when: ciao_dev is defined and ciao_dev

    - name: Remove CIAO user
      user:
        name: ciao
        state: absent
        remove: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Remove Ciao packages (Ubuntu)
      apt:
        name: "{{ item }}"
        state: absent
        autoremove: yes
        purge: yes
      with_items:
        - golang
        - git
        - openssl
        - qemu-kvm
        - xorriso
      when: ansible_distribution == 'Ubuntu'

    - name: Remove ciao bundles (ClearLinux)
      command: swupd bundle-remove {{ item }} {{ swupd_args | default('') }}
      args:
        removes: /usr/share/clear/bundles/{{ item }}
      with_items:
        - cloud-dashboard
        - cloud-control
        - cloud-network
        - nodejs-basic
        - kvm-host
        - libX11client
        - net-utils
        - os-core-dev
        - go-basic
      when: ansible_os_family == "Clear linux software for intel architecture"
