---
- hosts: openstack_identity
  tasks:
    - name: Set nginx_conf_dir
      set_fact: nginx_conf_dir='/etc/nginx'
      when: ansible_distribution == "Clear linux software for intel architecture"

    - name: Set nginx_conf_dir
      set_fact: nginx_conf_dir='/etc/nginx/conf.d'
      when: ansible_distribution == "Ubuntu"

    - name: Stop Keystone services
      service: name={{ item }} enabled=no state=stopped
      with_items:
        - uwsgi@keystone-public.socket
        - uwsgi@keystone-public.service
        - uwsgi@keystone-admin.socket
        - uwsgi@keystone-admin.service
        - nginx.service
        - memcached.service
      ignore_errors: yes

    - name: Remove Keystone files
      file: name={{ item }} state=absent
      with_items:
        - /etc/keystone/ssl
        - /etc/keystone/keystone.conf
        - "{{ nginx_conf_dir }}/keystone.conf"

    - name: Remove keystone files (ubuntu)
      file: name={{ item }} state=absent
      with_items:
        - /usr/share/uwsgi/keystone
        - /etc/systemd/system/uwsgi@.service
        - /etc/systemd/system/uwsgi@.socket
      when: ansible_distribution == 'Ubuntu'

    - name: Remove keystone packages (Ubuntu)
      apt:
        name: "{{ item }}"
        state: absent
        autoremove: yes
        purge: yes
      with_items:
        - nginx
        - keystone
        - memcached
        - uwsgi
        - uwsgi-plugin-python
      when: ansible_distribution == 'Ubuntu'

    - name: Remove keystone bundles (ClearLinux)
      command: swupd bundle-remove {{ item }} {{ swupd_args | default('') }}
      args:
        removes: /usr/share/clear/bundles/{{ item }}
      with_items:
        - openstack-identity
        - openstack-python-clients
        - openstack-common
      when: ansible_os_family == "Clear linux software for intel architecture"
