---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install openstack-identity bundle
  command: "swupd bundle-add openstack-identity {{ swupd_args }}"
  args:
    creates: /usr/share/clear/bundles/openstack-identity

- name: Verify openstack-identity has been installed
  command: "swupd verify -f {{ swupd_args }}"
  args:
    creates: /usr/bin/keystone-manage

- name: Install openstack-python-clients bundle
  command: "swupd bundle-add openstack-python-clients {{ swupd_args }}"
  args:
    creates: /usr/share/clear/bundles/openstack-python-clients

- name: Verify openstack-python-clients has been installed
  command: "swupd verify -f {{ swupd_args }}"
  args:
    creates: /usr/bin/openstack
