---
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  - name: Create Cinder ssl directory
    file: path=/etc/cinder/ssl/ state=directory

  - name: Generate Cinder certificate and key
    delegate_to: "{{ groups['openstack_identity'][0] }}"
    certificate:
      cadir: "/etc/keystone/ssl"
      hostname: "{{ cinder_hostname }}"
      subj: "{{ cinder_subject }}"
      p12password: "{{ cinder_p12password }}"

  - name: Copy certificate and key
    delegate_to: "{{ groups['openstack_identity'][0] }}"
    synchronize: src=/etc/keystone/ssl/server/{{ item }} dest=/etc/cinder/ssl
    with_items:
      - "{{ cinder_hostname }}.cert.pem"
      - "{{ cinder_hostname }}.key.pem"
